# Uncomment the next line to define a global platform for your project
platform :ios, '8.1'

target 'URExampleMovingTransition' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for URExampleMovingTransition
  pod 'URMovingTransitionAnimator', '~> 0.0.3'
  pod 'Reveal-SDK', :configurations => ['Debug']

end
